theme: jekyll-theme-cayman
title: St Theresa of Lisieux Church, Stansted
description: We are the Catholic parish of Stansted, part of the Diocese of Brentwood. We are proud to be belong to the universal Catholic Church.
show_downloads: false
